/**
 * The published guides, read straight out of the content files.
 *
 * The weekly issue is generated by a plain .mjs script, and the guides live in
 * TypeScript modules that import through the "@/" path alias. Node can strip
 * the types but cannot resolve that alias, so the script cannot simply import
 * them, and adding a loader for one email is a dependency the project does not
 * need. So the three fields the issue actually uses are read out of the source
 * text instead.
 *
 * That is a parser pointed at a moving file, which is only safe because
 * tests/posts-index.test.ts imports the real modules through vitest — which
 * does resolve the alias — and asserts this returns exactly the same slugs,
 * titles and dates. If a content file is ever reshaped, that test fails before
 * an issue can quote a guide that does not exist.
 */
import fs from "node:fs/promises";
import path from "node:path";

const FILES = ["src/content/posts.ts", "src/content/posts-cs.ts"];

function unquote(raw) {
  return raw.replace(/\\(["\\])/g, "$1");
}

/**
 * Comparison pages sit in the same file at the same indentation and also carry
 * a slug, so "has a publishedAt" is what separates a guide from one of them.
 * Keying off the array name instead would mean tracking where each array starts
 * and ends, which is the part most likely to drift.
 */
function parse(text) {
  const lines = text.split("\n");
  const starts = [];
  lines.forEach((l, i) => {
    if (/^ {4}slug: "/.test(l)) starts.push(i);
  });

  return starts
    .map((start, n) => {
      const end = n + 1 < starts.length ? starts[n + 1] : lines.length;
      const field = (name) => {
        for (let i = start; i < end; i += 1) {
          const m = lines[i].match(new RegExp(`^ {4}${name}: "(.*)",?$`));
          if (m) return unquote(m[1]);
        }
        return "";
      };
      return { slug: field("slug"), title: field("title"), publishedAt: field("publishedAt") };
    })
    .filter((p) => p.slug && p.title && p.publishedAt);
}

export async function readPostIndex(cwd = process.cwd()) {
  const out = [];
  for (const rel of FILES) {
    out.push(...parse(await fs.readFile(path.join(cwd, rel), "utf8")));
  }
  return out;
}

export { parse as parsePostsSource };
